### ISSUE TITLE
Can't edit "Artist" and other tags and editing makes m4a file unavailable 

### ISSUE THREAD

**Issue by jhoc2000** [vanilla-music/vanilla-music-tag-editor#34]
I've been able to open the Vanilla Tag Editor version 1.4.6 using Vanilla Music version 1.0.85 on my Xiaomi Pocophone F1 running LineageOS 17.x (please see attached image) but editing the "Song artist" tag doesn't change the "Artist" value in the song (see image) . I then tried to edit the "Artist" value but I can't enter anything for that value when I select it (see image). In fact I can't enter any information for any of the tags except the four shown in the image.

Also, after editing the "Song title" and, apparently, successfully saving the file, I can no longer play the m4a file, which is on the SDCard, using Vanilla Music. It just plays the next available song. I can see the file using a file browser but I can't open it using Vanilla Music. The Vanilla Tag Editor seems to corrupt the file. 

![Screenshot_20200428-172457_Vanilla_Tag_Editor](https://user-images.githubusercontent.com/16982707/80459253-724c3f80-8975-11ea-8a81-55f381f5a116.png)

**Comment by Adonai** [comment]
Try playing the file on your desktop. Does it work?

**Comment by jhoc2000** [comment]
I'm able to play the song directly from the phone's SDCard storage via Ubuntu 19.10 and VLC media player version 3.0.8.

I can't import the file into Rhythmbox version 3.4.3 on the same platform.

???

**Comment by Adonai** [comment]
Looks like some clients don't recognize metadata at the end of the file as valid, though specification allows that. I'll try to rewrite the implementation so it always writes it at the start of the file.

It won't be fast so if you want to help have a look at https://github.com/Adonai/jaudiotagger

**Comment by jhoc2000** [comment]
Thank you. I would like to be able to edit the metadata of the music files. 

I haven't written any Java code since the 90's so I don't think that I'll be much help other than testing?

**Comment by jhoc2000** [comment]
I think that this is related to the Vanilla Metadata Fetch plugin error at:

https://github.com/vanilla-music/vanilla-music-metadata-fetch/issues/5

In fact, I'm confused as to which plugin causes the different errors.

**Comment by Adonai** [comment]
Sorry for misleading comments. Each plugin does its part separately. Metadata fetcher plugin only fetches metadata for audio file. It then uses Tag Editor plugin to write the metadata to actual file. Only Tag Editor writes the file directly. So, both bugs are actually for Tag Editor and we should track them here.

Anyway, did version 1.4.7 help with this bug? Does writing mp4 work okay now?

**Comment by jhoc2000** [comment]
Okay. Thanks for clearing that up.

No. The music stops when I select "OK" after editing something with Tag Editor in version 1.4.7 and 1.4.8.

I start the song in Vanilla Music, open Tag Editor whilst the music is playing, change something like "Song artist" and when I select "OK", a popup window says "File written successfully", the music stops and Vanilla Music no longer recognises the song.

Interesting, I don't have to change anything using Tag Editor. The file becomes "corrupted" (for want of a better word) if I open Tag Editor and immediately select "OK".

I hope this helps.

**Comment by Adonai** [comment]
Okay, I think I fixed a couple more issues with editing mp4 files so can you please try version 1.4.9 once it's out?

**Comment by jhoc2000** [comment]
Of course. I'll check the Google Play Store daily for the next update.

Thanks.

**Comment by jhoc2000** [comment]
I've just updated the Tag Editor to version 1.4.9 and tried to edit an m4a file but when I selected "OK" the music stopped and Vanilla Music could no longer recognise the file.

Also, I still couldn't edit any fields other than those apparent in the form, as per the image above.

Should I send you the original file before it becomes corrupted? That way, you could test the error yourself.

**Comment by Adonai** [comment]
Please do. I don't see corruption issue on my m4a files, and Vanilla properly detects and plays them after they were edited. 

Vanilla stopping playback is probably due to the fact whole box-structure of m4a is getting rewritten, and this includes media chunk offsets. No way around this issue.

**Comment by jhoc2000** [comment]
Here is the m4a file renamed as a txt file.

[1. Assault & Battery Part I.txt](https://github.com/vanilla-music/vanilla-music-tag-editor/files/4642580/1.Assault.Battery.Part.I.txt)

Thank you for you help.

**Comment by Adonai** [comment]
I'll take a look on weekend

**Comment by Adonai** [comment]
Fixed in 1.4.10

**Comment by jhoc2000** [comment]
I have confirmed that I the m4a files are no longer corrupted by the writing to file using the Vanilla Tag Editor and Vanilla Metadata Fetch.

Thank you very much for fixing this. However, I still have problems editing the different tags. Do you wish for me to open another issue because this one has been closed?

**Comment by Adonai** [comment]
Yes, please do
